// Generated by `cargo run -p xtask -- bindings`. Do not edit.
//
// Mirrors the Rust types exported by `pipdock schema <T>` (CLI-SPEC §6). Regenerate after
// changing any of them; `cargo test` fails while this file is stale.
//
// Command signatures are not here — they are not derivable from a schema and stay hand-written
// in `./index.ts`.

/**
 * The package responsible for holding another one back.
 *
 * ARCHITECTURE §3: the engine's report says *what* was held back; *who* is responsible comes from
 * cross-referencing the reverse-dependency graph with each blocker's `Requires-Dist` constraint.
 * **If attribution is ambiguous, show the constraint without a culprit rather than guessing.**
 */
export interface Blocker {
  /** The package imposing the constraint, absent when attribution is ambiguous. */
  by?: PkgName | null;
  /** The constraint text, e.g. `"requests<2.31"`. */
  constraint: string;
}

/** One line of the preview diff. */
export interface Change {
  /** Version before, absent for a fresh install. */
  from?: Version | null;
  /** Which preview section this belongs in. */
  kind: ChangeKind;
  /** Normalized distribution name. */
  name: PkgName;
  /** Version the resolver chose. */
  to: Version;
}

/** Which section of the preview a change belongs to (UI-SPEC §4). */
export type ChangeKind =
  | 'upgrade'
  | 'new-dependency'
  | 'new-install'
  | 'downgrade';

/** One package whose version differs between two states. */
export interface ChangedEntry {
  /** What is installed now. */
  current: Version;
  /** The package. */
  name: PkgName;
  /** What the snapshot recorded. */
  snapshot: Version;
}

/** One unsatisfied requirement reported by `pip check` / `uv pip check`. */
export interface CheckFinding {
  /** The distribution whose requirement is unsatisfied. */
  pkg: PkgName;
  /** Human-readable requirement text as the engine printed it. */
  requirement: string;
}

/** Post-execution environment verification. */
export interface CheckReport {
  /** Details when `ok` is false. */
  findings?: CheckFinding[];
  /** True when the engine reported no broken requirements. */
  ok: boolean;
}

/**
 * Every code PipDock can surface at v1 launch.
 *
 * `docs/TESTING.md` §2 requires at least one captured stderr fixture per variant before ship;
 * the test that enforces "no code without fixture" lives beside the classifiers.
 */
export type Code =
  | 'PD-ENV-001'
  | 'PD-ENV-002'
  | 'PD-ENV-003'
  | 'PD-ENG-001'
  | 'PD-ENG-002'
  | 'PD-ENG-003'
  | 'PD-ENG-999'
  | 'PD-RES-001'
  | 'PD-RES-002'
  | 'PD-BLD-001'
  | 'PD-BLD-002'
  | 'PD-BLD-003'
  | 'PD-PKG-001'
  | 'PD-PKG-002'
  | 'PD-PKG-003'
  | 'PD-PKG-004'
  | 'PD-NET-001'
  | 'PD-NET-002'
  | 'PD-NET-010'
  | 'PD-NET-011'
  | 'PD-PRM-001'
  | 'PD-PRM-002'
  | 'PD-SNP-001'
  | 'PD-SNP-002'
  | 'PD-SYS-001'
  | 'PD-SYS-002'
  | 'PD-HLT-001'
  | 'PD-HLT-002'
  | 'PD-HLT-003'
  | 'PD-INT-001';

/** Aggregate counts rendered as "13 successful, 2 failed, 1 skipped" (DATA-FLOW §6). */
export interface Counts {
  /** Steps that failed, each with a catalog code. */
  failed: number;
  /** Steps that applied. */
  ok: number;
  /** Steps not attempted. */
  skipped: number;
}

/** The difference between two environment states. */
export interface Diff {
  /** Present now, absent in the snapshot. */
  added: PinnedSpec[];
  /** Present in both at different versions. */
  changed: ChangedEntry[];
  /** Present in the snapshot, absent now. */
  removed: PinnedSpec[];
}

/** An installed distribution, as read by `probe.py` or `<engine> list`. */
export interface Dist {
  /** Normalized distribution name. */
  name: PkgName;
  /** Raw `Requires-Dist` entries. The reverse-dependency graph is built from these. */
  requiresDist?: string[];
  /** Raw `Requires-Python` specifier, when declared. */
  requiresPython?: string | null;
  /**
   * Installed size in bytes, summed from the distribution's RECORD manifest.
   *
   * `None` means "not knowable", and is deliberately not `0`: `.egg-info` distributions have
   * no RECORD, and a PEP 660 editable install has one that lists only its import shim, so
   * summing it reports a few hundred bytes for a project of any size. Only `probe.py` can
   * supply this — `<engine> list --format=json` does not report it — so it is always `None`
   * on a `Dist` that came from an engine.
   *
   * A lower bound even when present: uncompressed bytes as recorded at install time,
   * excluding `__pycache__` written afterwards.
   */
  sizeBytes?: number | null;
  /** Installed version. */
  version: Version;
}

/** Which resolver PipDock is driving. */
export type EngineId =
  | 'pip'
  | 'uv';

/** How an environment was discovered. Surfaced as the source chip in the Environments screen. */
export type EnvSource =
  | 'registry'
  | 'py-launcher'
  | 'uv'
  | 'venv-scan'
  | 'manual';

/** Which of the two execution phases produced a result (ARCHITECTURE §8). */
export type ExecMode =
  | 'batch'
  | 'isolated';

/** The end-of-run report shown in the summary sheet and emitted by `--json`. */
export interface ExecutionSummary {
  /**
   * True when the user stopped this run part-way.
   *
   * ARCHITECTURE §7 words this as `Skipped(UserCancelled)`, but [`StepStatus`] is a
   * payload-free enum and giving it one changes the wire shape for every consumer. A flag on
   * the summary also matches what the summary sheet actually needs: "cancelled" is said once
   * at the top, not repeated on forty rows.
   *
   * Steps that never ran are `Skipped`, which is already the honest status for them.
   */
  cancelled?: boolean;
  /** Post-run `engine.check()`. */
  check: CheckReport;
  /** Derived from `results`; see [`ExecutionSummary::tally`]. */
  counts: Counts;
  /** Which phase produced these results. */
  phase: ExecMode;
  /** Correlates the summary with its snapshot and log ring buffer. */
  planId: string;
  /** One row per package. */
  results?: StepResult[];
}

/**
 * What the uninstall guard found.
 *
 * Rationale from DATA-FLOW §5: bare `pip uninstall` performs **no** dependency check at all, so
 * this is a core value-add rather than a nicety. It is computed once against the full set,
 * because removing A and B together is fine when only B depends on A — asking per package would
 * raise a warning the user cannot act on.
 */
export interface GuardReport {
  /** For each package that has them, the installed packages that would break. */
  breaks: Record<string, PkgName[]>;
  /** The set the user asked to remove. */
  removing: PkgName[];
  /**
   * The removal set expanded to include everything that depends on it, transitively — the
   * "remove dependents too" option.
   */
  withDependents: PkgName[];
}

/** A package the resolver could not take all the way to `latest`. */
export interface HeldBack {
  /** Why it could not go further. Empty means the engine gave no attributable reason. */
  blockers?: Blocker[];
  /** The version the index offers. */
  latest: Version;
  /** Normalized distribution name. */
  pkg: PkgName;
  /** The version the resolver settled on. */
  resolved: Version;
}

/** One search result. */
export interface Hit {
  /** The name as PyPI spells it, for display. */
  display: string;
  /** Why it ranked where it did. Exposed so the UI can group exact and prefix matches visually. */
  kind: MatchKind;
  /** The normalized name, which is what every other module keys on. */
  name: PkgName;
}

/** A `ResolutionImpossible` outcome and whatever detail the engine gave (`PD-RES-001`). */
export interface ImpossibleDetail {
  /** The engine's own explanation, verbatim. */
  explanation: string;
  /** Packages involved in the unsatisfiable set. */
  packages?: PkgName[];
}

/** How a hit matched, in ranking order. */
export type MatchKind =
  | 'exact'
  | 'prefix'
  | 'fuzzy';

/** An installed distribution with a newer release available. */
export interface OutdatedDist {
  /** Currently installed version. */
  current: Version;
  /** Newest version the index offers. */
  latest: Version;
  /** Normalized distribution name. */
  name: PkgName;
}

/** Cached PyPI metadata for one package (ARCHITECTURE §5). */
export interface PackageMeta {
  /** Project home page, when declared. */
  homePage?: string | null;
  /** License text or identifier. */
  license?: string | null;
  /** Normalized name. */
  name: string;
  /** `Requires-Python` specifier. */
  requiresPython?: string | null;
  /** One-line description. */
  summary?: string | null;
  /** Newest release. */
  version?: string | null;
}

/** A pin with the reason the user gave for it. */
export interface Pin {
  /** How it is constrained. */
  mode: PinMode;
  /** The pinned package. */
  pkg: PkgName;
  /**
   * Free-text justification shown in the Pins screen.
   *
   * Worth storing even though nothing reads it programmatically: a pin without a reason
   * becomes a mystery the user is afraid to remove, and so stays forever.
   */
  reason?: string | null;
}

/** How a pin constrains a package. */
export type PinMode =
  | 'exclude'
  | { hold: { version: Version } };

/** A resolved, exact `name==version` pair. Only these reach a mutating engine command. */
export interface PinnedSpec {
  /** Normalized distribution name. */
  name: PkgName;
  /** The exact version the resolver chose. */
  version: Version;
}

/**
 * A PEP 503-normalized distribution name.
 *
 * Constructing one is the *only* way a package name reaches an argv array, which is what makes
 * SECURITY §2's "validated before it reaches argv" claim structural rather than aspirational.
 */
export type PkgName = string;

/** The user's intent, before the engine has said anything about it. */
export interface PlanRequest {
  /** New packages queued in the dock bay. */
  installs?: Spec[];
  /** Conflict-handling strategy. */
  strategy: Strategy;
  /** Already-installed packages the user selected for upgrade. */
  upgrades?: PkgName[];
}

/** A Python environment PipDock can act on. */
export interface PyEnv {
  /**
   * PEP 668 marker present. When true, mutation is blocked unless the user enabled the
   * Settings override (`PD-ENV-002`, SECURITY §3).
   */
  externallyManaged: boolean;
  /**
   * User site-packages directory that `probe.py -I` is hiding, when there is one.
   *
   * Owner decision 2026-07-27 (SP-6): the probe keeps running isolated, so on a non-venv
   * system Python it reports fewer distributions than `pip list` does. `Some` means packages
   * really are hidden and the Installed screen shows a note naming this path; `None` — always
   * the case inside a venv — means the listing is complete.
   */
  hiddenUserSite?: string | null;
  /** Canonicalized path to the interpreter. Never a shell string — see SECURITY §2. */
  interpreter: string;
  /** `sys.prefix` as reported by `probe.py`. */
  prefix: string;
  /** e.g. `"3.12.4"`. */
  pythonVersion: string;
  /** Where this env came from. */
  source: EnvSource;
}

/**
 * The normalized dry-run result.
 *
 * **Both adapters must emit this same shape** — that is the whole point of the `Engine` trait
 * (ARCHITECTURE §3). The pip adapter fills it from `--dry-run --report` JSON; the uv adapter from
 * uv's text plan output.
 *
 * The exact field set is **provisional until spike SP-1** confirms uv's output is rich enough to
 * populate `held_back.blockers`. If it is not, SP-1's go/no-go says v1.0 ships pip-primary with uv
 * behind a beta flag.
 */
export interface ResolutionReport {
  /** Everything that would change if the user confirms. */
  changes?: Change[];
  /** Packages that could not reach `latest`, with attribution. */
  heldBack?: HeldBack[];
  /** Present when the whole resolution failed. */
  impossible?: ImpossibleDetail | null;
  /** The engine's untouched output, kept for the log and for bug reports. */
  raw: string;
}

/**
 * The `.meta.json` sidecar (ARCHITECTURE §6).
 *
 * This type serves twice: it is the on-disk sidecar *and* what `snapshot list --json` emits, so
 * it is in `SCHEMA_TYPES`. The camelCase spelling is the wire contract, and the `alias`
 * attributes are what keep sidecars written before that change readable — a snapshot that no
 * longer parses is a rollback the user silently cannot perform, which is the one failure this
 * module exists to prevent. Removable once no pre-1.0 snapshot can plausibly still be on disk.
 */
export interface SnapshotMeta {
  /** PipDock's version, so an old snapshot can be interpreted by a newer build. */
  appVersion: string;
  /** When it was taken, RFC 3339. */
  createdAt: string;
  /**
   * Which engine produced the freeze.
   *
   * Load-bearing: pip freezes with `--all` and includes pip/setuptools, uv has no such flag and
   * omits them (DATA-FLOW §7). Without this, a diff across engines would read as "pip was
   * uninstalled".
   */
  engine: EngineId;
  /** Snapshot id, which is also its filename stem. */
  id: string;
  /** How many distributions the freeze recorded. */
  packageCount: number;
  /** Why it was taken. */
  trigger: Trigger;
}

/** What the user asked for: a name, optionally constrained. */
export interface Spec {
  /** Normalized distribution name. */
  name: PkgName;
  /** PEP 440 specifier such as `">=2,<3"`, or `None` for "latest". */
  versionReq?: string | null;
}

/** One row of the summary report (DATA-FLOW §6). */
export interface StepResult {
  /** Catalog code, present exactly when `status` is `Failed`. */
  code?: Code | null;
  /** Version before the step, absent for a fresh install. */
  from?: Version | null;
  /** Normalized distribution name. */
  pkg: PkgName;
  /** Whether it applied. */
  status: StepStatus;
  /** Tail of the engine's stderr for the failure detail pane. */
  stderrTail?: string | null;
  /** Version the step targeted. */
  to?: Version | null;
}

/** Outcome of a single package's step. */
export type StepStatus =
  | 'ok'
  | 'failed'
  | 'skipped';

/** How aggressively to resolve conflicts. */
export type Strategy =
  | 'compatible'
  | { 'force-latest': { overrides: PkgName[] } };

/** What caused a snapshot to be taken. Shown as the trigger label on the timeline (UI-SPEC §4). */
export type Trigger =
  | { plan: { planId: string } }
  | { rollback: { restoring: string } }
  | 'manual';

/** A version string as the engine reported it. Never reshaped or localized (I18N §2). */
export type Version = string;
