// Generated by `cargo run -p xtask -- bindings`. Do not edit.
//
// Mirrors the Rust types exported by `pipdock schema <T>` (CLI-SPEC §6). Regenerate after
// changing any of them; `cargo test` fails while this file is stale.
//
// Command signatures are not here — they are not derivable from a schema and stay hand-written
// in `./index.ts`.

/**
 * The package responsible for holding another one back.
 *
 * ARCHITECTURE §3: the engine's report says *what* was held back; *who* is responsible comes from
 * cross-referencing the reverse-dependency graph with each blocker's `Requires-Dist` constraint.
 * **If attribution is ambiguous, show the constraint without a culprit rather than guessing.**
 */
export interface Blocker {
  /** The package imposing the constraint, absent when attribution is ambiguous. */
  by?: PkgName | null;
  /** The constraint text, e.g. `"requests<2.31"`. */
  constraint: string;
}

/**
 * One installed package that a removal would break, and the requirement that says so.
 *
 * `constraint` is the **bare specifier tail** — `"<2,>=1.26.0"`, not `"numpy<2,>=1.26.0"` —
 * because [`Requirement::parse`] splits the distribution name off and the name is already the key
 * of [`GuardReport::breaks`]. The head that goes in front of it is the package being removed, so
 * the caller has both halves and can join them the way its own language does. Rust does not
 * assemble the sentence: I18N §1 keeps every word of phrasing in the frontend catalogs, and a
 * specifier is data, like a version or a path.
 */
export interface BrokenDependent {
  /** The version specifier it declared, e.g. `"<2,>=1.26.0"`. Empty when unconstrained. */
  constraint: string;
  /** The installed package that would be left with a missing dependency. */
  pkg: PkgName;
  /**
   * Its installed version, when the graph knows it — so the dialog can say `pandas 2.1.4`
   * rather than bare `pandas`, which is what makes the constraint checkable by hand.
   */
  version?: string | null;
}

/** One line of the preview diff. */
export interface Change {
  /** Version before, absent for a fresh install. */
  from?: Version | null;
  /** Which preview section this belongs in. */
  kind: ChangeKind;
  /** Normalized distribution name. */
  name: PkgName;
  /** Version the resolver chose. */
  to: Version;
}

/** Which section of the preview a change belongs to (UI-SPEC §4). */
export type ChangeKind =
  | 'upgrade'
  | 'new-dependency'
  | 'new-install'
  | 'downgrade';

/** One package whose version differs between two states. */
export interface ChangedEntry {
  /** What is installed now. */
  current: Version;
  /** The package. */
  name: PkgName;
  /** What the snapshot recorded. */
  snapshot: Version;
}

/** One unsatisfied requirement reported by `pip check` / `uv pip check`. */
export interface CheckFinding {
  /** The distribution whose requirement is unsatisfied. */
  pkg: PkgName;
  /** Human-readable requirement text as the engine printed it. */
  requirement: string;
}

/** Post-execution environment verification. */
export interface CheckReport {
  /** Details when `ok` is false. */
  findings?: CheckFinding[];
  /** True when the engine reported no broken requirements. */
  ok: boolean;
}

/**
 * Every code PipDock can surface at v1 launch.
 *
 * `docs/TESTING.md` §2 requires at least one captured stderr fixture per variant before ship;
 * the test that enforces "no code without fixture" lives beside the classifiers.
 */
export type Code =
  | 'PD-ENV-001'
  | 'PD-ENV-002'
  | 'PD-ENV-003'
  | 'PD-ENG-001'
  | 'PD-ENG-002'
  | 'PD-ENG-003'
  | 'PD-ENG-999'
  | 'PD-RES-001'
  | 'PD-RES-002'
  | 'PD-RES-003'
  | 'PD-RES-004'
  | 'PD-BLD-001'
  | 'PD-BLD-002'
  | 'PD-BLD-003'
  | 'PD-PKG-001'
  | 'PD-PKG-002'
  | 'PD-PKG-003'
  | 'PD-PKG-004'
  | 'PD-NET-001'
  | 'PD-NET-002'
  | 'PD-NET-010'
  | 'PD-NET-011'
  | 'PD-PRM-001'
  | 'PD-PRM-002'
  | 'PD-PRM-003'
  | 'PD-SNP-001'
  | 'PD-SNP-002'
  | 'PD-SYS-001'
  | 'PD-SYS-002'
  | 'PD-HLT-001'
  | 'PD-HLT-002'
  | 'PD-HLT-003'
  | 'PD-HLT-004'
  | 'PD-INT-001';

/** Aggregate counts rendered as "13 successful, 2 failed, 1 skipped" (DATA-FLOW §6). */
export interface Counts {
  /** Steps that failed, each with a catalog code. */
  failed: number;
  /** Steps that applied. */
  ok: number;
  /** Steps not attempted. */
  skipped: number;
}

/** What the user chose for one package that needs a decision (DATA-FLOW §3, CLI-SPEC §4). */
export type Decision =
  | 'keep-compatible'
  | 'skip'
  | 'force-latest';

/**
 * Where the project declares its dependencies, if anywhere.
 *
 * deptry needs one of these to have anything to compare against. `None` is not an error — it is
 * the "limited-mode notice" §3 asks the UI to show, and the other two tools do not care.
 */
export type DeclaredSource =
  | { kind: 'pyproject' }
  | { files: string[]; kind: 'requirements' }
  | { kind: 'none' };

/**
 * One deptry violation, grouped by the dependency it is about.
 *
 * **deptry emits a flat list**, one object per `(code, module, location)`:
 * `{"error":{"code","message"},"module","location":{"file","line","column"}}`. §5 sketched a
 * per-dependency object with a `locations` array; that shape does not exist. Grouping happens here
 * rather than in the UI so the GUI, `pipdock health --json` and P4's saved report cannot disagree.
 */
export interface DeptryIssue {
  /** deptry's own code — `DEP001`..`DEP004`. Never a PipDock catalog code. */
  code: string;
  /**
   * The name deptry reported.
   *
   * **A module name, not necessarily a distribution.** `yaml` is `PyYAML`, `cv2` is
   * `opencv-python`. Anything handing this to a package operation has to reconcile it first.
   */
  dep: string;
  /** Where it was found. Empty when deptry named no location. */
  locations?: SourceLocation[];
  /**
   * deptry's message, verbatim.
   *
   * Not a `kind` derived from the code: that mapping would be PipDock's, maintained in two
   * languages, against a tool that adds codes on its own schedule.
   */
  message: string;
}

/** The difference between two environment states. */
export interface Diff {
  /** Present now, absent in the snapshot. */
  added: PinnedSpec[];
  /** Present in both at different versions. */
  changed: ChangedEntry[];
  /** Present in the snapshot, absent now. */
  removed: PinnedSpec[];
}

/** An installed distribution, as read by `probe.py` or `<engine> list`. */
export interface Dist {
  /** Normalized distribution name. */
  name: PkgName;
  /** Raw `Requires-Dist` entries. The reverse-dependency graph is built from these. */
  requiresDist?: string[];
  /** Raw `Requires-Python` specifier, when declared. */
  requiresPython?: string | null;
  /**
   * Installed size in bytes, summed from the distribution's RECORD manifest.
   *
   * `None` means "not knowable", and is deliberately not `0`: `.egg-info` distributions have
   * no RECORD, and a PEP 660 editable install has one that lists only its import shim, so
   * summing it reports a few hundred bytes for a project of any size. Only `probe.py` can
   * supply this — `<engine> list --format=json` does not report it — so it is always `None`
   * on a `Dist` that came from an engine.
   *
   * A lower bound even when present: uncompressed bytes as recorded at install time,
   * excluding `__pycache__` written afterwards.
   */
  sizeBytes?: number | null;
  /** Installed version. */
  version: Version;
}

/** Which resolver PipDock is driving. */
export type EngineId =
  | 'pip'
  | 'uv';

/** Availability and version of an engine for a given environment. */
export interface EngineInfo {
  /** False means the binary or module could not be found (`PD-ENG-001`). */
  available: boolean;
  /** Which engine this describes. */
  id: EngineId;
  /** Reported version, absent when the engine is not available. */
  version?: string | null;
}

/** How an environment was discovered. Surfaced as the source chip in the Environments screen. */
export type EnvSource =
  | 'registry'
  | 'py-launcher'
  | 'uv'
  | 'venv-scan'
  | 'manual';

/** Which of the two execution phases produced a result (ARCHITECTURE §8). */
export type ExecMode =
  | 'batch'
  | 'isolated';

/** The end-of-run report shown in the summary sheet and emitted by `--json`. */
export interface ExecutionSummary {
  /**
   * True when the user stopped this run part-way.
   *
   * ARCHITECTURE §7 words this as `Skipped(UserCancelled)`, but [`StepStatus`] is a
   * payload-free enum and giving it one changes the wire shape for every consumer. A flag on
   * the summary also matches what the summary sheet actually needs: "cancelled" is said once
   * at the top, not repeated on forty rows.
   *
   * Steps that never ran are `Skipped`, which is already the honest status for them.
   */
  cancelled?: boolean;
  /** Post-run `engine.check()`. */
  check: CheckReport;
  /** Derived from `results`; see [`ExecutionSummary::tally`]. */
  counts: Counts;
  /** Which phase produced these results. */
  phase: ExecMode;
  /** Correlates the summary with its snapshot and log ring buffer. */
  planId: string;
  /** One row per package. */
  results?: StepResult[];
}

/**
 * How safe ruff considers its own fix.
 *
 * Only `Safe` is ever applied: P5 runs plain `ruff check --fix`, which is what `--unsafe-fixes`
 * exists to opt out of, and CODE-HEALTH-SPEC §1 makes the write path the narrow one.
 */
export type FixApplicability =
  | 'safe'
  | 'unsafe'
  | 'display';

/**
 * What a fix did.
 *
 * The only type in this module on the wire, so the only one in `SCHEMA_TYPES`.
 */
export interface FixReport {
  /** Uncommitted entries the user waived, when they waived any. */
  dirtyBefore?: number | null;
  /**
   * How many files ruff was asked to rewrite.
   *
   * **Derived from the pre-fix findings' distinct filenames, never parsed out of ruff's
   * "Fixed N errors in M files".** A count that comes from data cannot drift with wording, and
   * that sentence is on stderr where a format change would silently take it away.
   */
  filesChanged: number;
  /** RFC 3339. */
  fixedAt: string;
  /**
   * Safe fixes that survived, which means something was not written.
   *
   * Not an error: the tree has already changed, and failing here would discard the report that
   * says what happened. `ensure_writable` is what makes this rare; this is what makes it
   * visible when it happens anyway.
   */
  notApplied: number;
  /**
   * What ruff still reports afterwards, from its own post-fix run.
   *
   * Lets the tab refresh without a second Run — and, because the fix and the re-report are one
   * invocation, without a window in which the two could disagree.
   */
  remaining: RuffFindings;
}

/**
 * What the flow needs next.
 *
 * Crosses IPC, so the GUI's two decision points are a round trip apart (see the module docs).
 * Tagged on `step` rather than externally, because the frontend switches on it and a bare
 * `{ needsDecisions: { … } }` would make every consumer unwrap before it can look.
 */
export type FlowStep =
  | { report: ResolutionReport; round: number; roundsRemaining: number; step: 'needsDecisions' }
  | { report: ResolutionReport; step: 'needsConfirm' }
  | { report: ResolutionReport; step: 'roundsExhausted' }
  | { reason: NothingReason; step: 'nothing' };

/** How fresh a metadata answer is, so the UI can badge it (UI-SPEC §7). */
export type Freshness =
  | 'fresh'
  | 'cached'
  | 'stale';

/**
 * What the uninstall guard found.
 *
 * Rationale from DATA-FLOW §5: bare `pip uninstall` performs **no** dependency check at all, so
 * this is a core value-add rather than a nicety. It is computed once against the full set,
 * because removing A and B together is fine when only B depends on A — asking per package would
 * raise a warning the user cannot act on.
 */
export interface GuardReport {
  /** For each package that has them, the installed packages that would break and why. */
  breaks: Record<string, BrokenDependent[]>;
  /** The set the user asked to remove. */
  removing: PkgName[];
  /**
   * The removal set expanded to include everything that depends on it, transitively — the
   * "remove dependents too" option.
   */
  withDependents: PkgName[];
}

/**
 * A Code Health run, whole or partial.
 *
 * The only type in this module that reaches the wire, so the only one in `SCHEMA_TYPES` — the
 * bindings generator hoists everything it references out of `$defs` into its own TS declaration.
 */
export interface HealthReport {
  /** What the project declares its dependencies in (§3's detection order). */
  declared: DeclaredSource;
  /** deptry's findings, grouped by dependency. */
  deptry: DeptryIssue[];
  /** `canonical_interpreter` of the environment deptry compared against. */
  env: string;
  /**
   * Why a requested tool contributed nothing.
   *
   * **Empty means every tool in `ran` completed.** This is what makes `PD-HLT-003`'s "partial
   * report shown" a shape rather than a promise: one tool failing does not fail the run, it
   * lands here and the other two still report.
   */
  problems?: ToolProblem[];
  /** Absolute project folder the tools ran in. Data, never localized (I18N §2). */
  project: string;
  /**
   * Which tools were asked to run.
   *
   * **What makes an empty list readable.** Without it, "no deptry findings" and "deptry never
   * ran" are the same empty array, and the UI would have to render one as the other — which is
   * the "never render a state you have not loaded" rule applied to a tab.
   */
  ran: string[];
  /** When the run finished, RFC 3339. */
  ranAt: string;
  /** ruff's findings, plus the counts P5's confirm dialog needs. */
  ruff: RuffFindings;
  /** The version each tool reported, out of the tools manifest. */
  toolVersions: Record<string, string>;
  /** vulture's findings, in the order it reported them. */
  vulture: VultureFinding[];
}

/** A package the resolver could not take all the way to `latest`. */
export interface HeldBack {
  /** Why it could not go further. Empty means the engine gave no attributable reason. */
  blockers?: Blocker[];
  /** The version the index offers. */
  latest: Version;
  /** Normalized distribution name. */
  pkg: PkgName;
  /** The version the resolver settled on. */
  resolved: Version;
}

/** One search result. */
export interface Hit {
  /** The name as PyPI spells it, for display. */
  display: string;
  /** Why it ranked where it did. Exposed so the UI can group exact and prefix matches visually. */
  kind: MatchKind;
  /** The normalized name, which is what every other module keys on. */
  name: PkgName;
}

/** A `ResolutionImpossible` outcome and whatever detail the engine gave (`PD-RES-001`). */
export interface ImpossibleDetail {
  /** The engine's own explanation, verbatim. */
  explanation: string;
  /** Packages involved in the unsatisfiable set. */
  packages?: PkgName[];
}

/**
 * What the user asked for, before it becomes a [`PlanRequest`].
 *
 * Names arrive as strings and are parsed here rather than by the caller, so both heads get the
 * same `PD-PKG-002` on a malformed name and SECURITY §2's "validated before it reaches argv"
 * holds for the GUI as well as the CLI.
 */
export type Intent =
  | { all: boolean; except?: string[]; forceLatest?: boolean; intent: 'update'; pkgs?: string[] }
  | { intent: 'install'; specs: string[] };

/** How a hit matched, in ranking order. */
export type MatchKind =
  | 'exact'
  | 'prefix'
  | 'fuzzy';

/** Why a flow ended before there was anything to confirm. */
export type NothingReason =
  | 'nothing-to-do'
  | 'everything-skipped';

/** An installed distribution with a newer release available. */
export interface OutdatedDist {
  /** Currently installed version. */
  current: Version;
  /** Newest version the index offers. */
  latest: Version;
  /** Normalized distribution name. */
  name: PkgName;
}

/** Cached PyPI metadata for one package (ARCHITECTURE §5). */
export interface PackageMeta {
  /** Project home page, when declared. */
  homePage?: string | null;
  /** License text or identifier. */
  license?: string | null;
  /** Normalized name. */
  name: string;
  /** `Requires-Python` specifier. */
  requiresPython?: string | null;
  /** One-line description. */
  summary?: string | null;
  /** Newest release. */
  version?: string | null;
}

/** What [`parse`] made of a file. */
export interface ParsedRequirements {
  /** Everything else, with its line number and reason. */
  skipped: SkippedLine[];
  /** Install specs, in file order, as `Intent::Install` wants them. */
  specs: string[];
}

/** A pin with the reason the user gave for it. */
export interface Pin {
  /** How it is constrained. */
  mode: PinMode;
  /** The pinned package. */
  pkg: PkgName;
  /**
   * Free-text justification shown in the Pins screen.
   *
   * Worth storing even though nothing reads it programmatically: a pin without a reason
   * becomes a mystery the user is afraid to remove, and so stays forever.
   */
  reason?: string | null;
}

/** How a pin constrains a package. */
export type PinMode =
  | 'exclude'
  | { hold: { version: Version } };

/** A package worth pinning, and why — PRD P1-2, UI-SPEC §4. */
export interface PinSuggestion {
  /**
   * How many installed packages depend on it.
   *
   * The number is the whole argument, so it is carried rather than recomputed for display:
   * "12 packages depend on it" is what makes the suggestion actionable, and a count the screen
   * derived separately would eventually disagree with the one that qualified it.
   */
  dependents: number;
  /** The package being suggested. */
  pkg: PkgName;
}

/** A resolved, exact `name==version` pair. Only these reach a mutating engine command. */
export interface PinnedSpec {
  /** Normalized distribution name. */
  name: PkgName;
  /** The exact version the resolver chose. */
  version: Version;
}

/**
 * A PEP 503-normalized distribution name.
 *
 * Constructing one is the *only* way a package name reaches an argv array, which is what makes
 * SECURITY §2's "validated before it reaches argv" claim structural rather than aspirational.
 */
export type PkgName = string;

/** The user's intent, before the engine has said anything about it. */
export interface PlanRequest {
  /** New packages queued in the dock bay. */
  installs?: Spec[];
  /** Conflict-handling strategy. */
  strategy: Strategy;
  /** Already-installed packages the user selected for upgrade. */
  upgrades?: PkgName[];
}

/**
 * One event on the `plan-progress` channel (ARCHITECTURE §7).
 *
 * Deferred from Stage 1 to the slice that could verify it. It was a bare line, which made two
 * documented features unimplementable: UI-SPEC §3's per-package section markers in the console
 * drawer had nothing to mark a section with, and §8's "13 of 15 complete" live region had no
 * event that meant "one finished". Neither can be recovered from the text — an engine's output
 * does not reliably say which package it is about, and counting lines is not counting steps.
 *
 * A tagged lifecycle instead: every step emits exactly one [`Self::StepStarted`], any number of
 * [`Self::Line`]s, and exactly one [`Self::StepFinished`]. That makes the drawer's grouping and
 * the live region's counter both mechanical rather than inferred.
 */
export type ProgressEvent =
  | { kind: 'stepStarted'; phase: ExecMode; pkg?: PkgName | null; step: number; total: number }
  | { kind: 'line'; line: string; phase: ExecMode; pkg?: PkgName | null; step: number; stream: Stream }
  | { kind: 'stepFinished'; phase: ExecMode; pkg?: PkgName | null; status: StepStatus; step: number; total: number };

/** A Python environment PipDock can act on. */
export interface PyEnv {
  /**
   * PEP 668 marker present. When true, mutation is blocked unless the user enabled the
   * Settings override (`PD-ENV-002`, SECURITY §3).
   */
  externallyManaged: boolean;
  /**
   * User site-packages directory that `probe.py -I` is hiding, when there is one.
   *
   * Owner decision 2026-07-27 (SP-6): the probe keeps running isolated, so on a non-venv
   * system Python it reports fewer distributions than `pip list` does. `Some` means packages
   * really are hidden and the Installed screen shows a note naming this path; `None` — always
   * the case inside a venv — means the listing is complete.
   */
  hiddenUserSite?: string | null;
  /** Canonicalized path to the interpreter. Never a shell string — see SECURITY §2. */
  interpreter: string;
  /** `sys.prefix` as reported by `probe.py`. */
  prefix: string;
  /** e.g. `"3.12.4"`. */
  pythonVersion: string;
  /** Where this env came from. */
  source: EnvSource;
}

/** What a refresh did. */
export interface RefreshReport {
  /** How long the whole refresh took. */
  elapsedMs: number;
  /** Projects ingested. */
  projects: number;
  /** Bytes received on the wire. */
  wireBytes: number;
}

/**
 * The normalized dry-run result.
 *
 * **Both adapters must emit this same shape** — that is the whole point of the `Engine` trait
 * (ARCHITECTURE §3). The pip adapter fills it from `--dry-run --report` JSON; the uv adapter from
 * uv's text plan output.
 *
 * The exact field set is **provisional until spike SP-1** confirms uv's output is rich enough to
 * populate `held_back.blockers`. If it is not, SP-1's go/no-go says v1.0 ships pip-primary with uv
 * behind a beta flag.
 */
export interface ResolutionReport {
  /** Everything that would change if the user confirms. */
  changes?: Change[];
  /** Packages that could not reach `latest`, with attribution. */
  heldBack?: HeldBack[];
  /** Present when the whole resolution failed. */
  impossible?: ImpossibleDetail | null;
  /** The engine's untouched output, kept for the log and for bug reports. */
  raw: string;
}

/** The operations that would restore a snapshot. */
export interface RollbackPlan {
  /** Packages to install at the snapshot's versions. */
  install: PinnedSpec[];
  /** Packages to remove: present now, absent in the snapshot. */
  uninstall: PkgName[];
}

/**
 * What a rollback would do, for the caller to show before it happens.
 *
 * Crosses IPC, so DATA-FLOW §8's "user may proceed partially" is a decision the user makes
 * looking at the same three things the flow holds: which snapshot, what it would do, and what it
 * cannot put back.
 */
export interface RollbackPreview {
  /** The minimal set of operations to get there. */
  restore: RollbackPlan;
  /** The snapshot being restored. */
  target: SnapshotMeta;
  /**
   * Freeze lines no index can restore — editable installs, direct URLs (`PD-SNP-002`).
   *
   * Reported rather than dropped: a rollback that silently leaves these behind is a success
   * message for a restore that did not fully happen.
   */
  unrestorable: string[];
}

/** One ruff finding. */
export interface RuffFinding {
  /**
   * The rule code, e.g. `F401`.
   *
   * Optional because the field is not ours. ruff 0.16.2 always sets it — a syntax error comes
   * through as `invalid-syntax` rather than null, which is **not** what CODE-HEALTH-SPEC §6
   * assumed — but tolerating null costs one `??` in the UI and stops a format change from
   * failing every run.
   */
  code?: string | null;
  /** 1-based. */
  column: number;
  /** Absolute, as ruff reports it. */
  filename: string;
  /** Whether ruff offers a fix, and how confident it is in it. */
  fix?: FixApplicability | null;
  /** ruff's message, verbatim. */
  message: string;
  /** The rule slug, e.g. `unused-import`. */
  name: string;
  /** 1-based. */
  row: number;
  /**
   * ruff's own documentation link.
   *
   * **Carried, never constructed.** The URL is keyed by rule *name*, so §6's
   * `https://docs.astral.sh/ruff/rules/<code>` 404s — `I001` lives at `.../unsorted-imports`.
   * Null for a syntax error, which has no rule page.
   */
  url?: string | null;
}

/** ruff's findings and the two counts the fix path is built on. */
export interface RuffFindings {
  /** Every finding, in ruff's order. */
  findings: RuffFinding[];
  /**
   * How many carry a **safe** fix — what `ruff check --fix` would actually apply.
   *
   * Counted here rather than in the UI because P5's confirm dialog and the CLI's prompt have to
   * name the same number, and two implementations of "count the safe ones" will not stay equal.
   */
  fixable: number;
  /** How many distinct files those touch. The number P5's dialog names. */
  fixableFiles: number;
}

/** Why a line was not turned into a spec. */
export type SkipReason =
  | 'include'
  | 'not-from-index'
  | 'option'
  | 'unparsed';

/** A line the parser would not turn into an install spec, and what was wrong with it. */
export interface SkippedLine {
  /** 1-based, so it matches what an editor shows. */
  line: number;
  /** Why, as a catalog-style discriminant the UI turns into a sentence. */
  reason: SkipReason;
  /** The line, trimmed. Data — shown verbatim, never translated (I18N §2). */
  text: string;
}

/**
 * The `.meta.json` sidecar (ARCHITECTURE §6).
 *
 * This type serves twice: it is the on-disk sidecar *and* what `snapshot list --json` emits, so
 * it is in `SCHEMA_TYPES`. The camelCase spelling is the wire contract, and the `alias`
 * attributes are what keep sidecars written before that change readable — a snapshot that no
 * longer parses is a rollback the user silently cannot perform, which is the one failure this
 * module exists to prevent. Removable once no pre-1.0 snapshot can plausibly still be on disk.
 */
export interface SnapshotMeta {
  /** PipDock's version, so an old snapshot can be interpreted by a newer build. */
  appVersion: string;
  /** When it was taken, RFC 3339. */
  createdAt: string;
  /**
   * Which engine produced the freeze.
   *
   * Load-bearing: pip freezes with `--all` and includes pip/setuptools, uv has no such flag and
   * omits them (DATA-FLOW §7). Without this, a diff across engines would read as "pip was
   * uninstalled".
   */
  engine: EngineId;
  /** Snapshot id, which is also its filename stem. */
  id: string;
  /** How many distributions the freeze recorded. */
  packageCount: number;
  /** Why it was taken. */
  trigger: Trigger;
}

/** A file and, when the tool knew it, a position in it. */
export interface SourceLocation {
  /** 1-based. */
  column?: number | null;
  /** Relative to the project folder where the tool reported it that way. */
  file: string;
  /** 1-based. Absent for a whole-file finding such as an unused dependency in `pyproject.toml`. */
  line?: number | null;
}

/** What the user asked for: a name, optionally constrained. */
export interface Spec {
  /** Normalized distribution name. */
  name: PkgName;
  /** PEP 440 specifier such as `">=2,<3"`, or `None` for "latest". */
  versionReq?: string | null;
}

/** One row of the summary report (DATA-FLOW §6). */
export interface StepResult {
  /** Catalog code, present exactly when `status` is `Failed`. */
  code?: Code | null;
  /** Version before the step, absent for a fresh install. */
  from?: Version | null;
  /** Normalized distribution name. */
  pkg: PkgName;
  /** Whether it applied. */
  status: StepStatus;
  /** Tail of the engine's stderr for the failure detail pane. */
  stderrTail?: string | null;
  /** Version the step targeted. */
  to?: Version | null;
}

/** Outcome of a single package's step. */
export type StepStatus =
  | 'ok'
  | 'failed'
  | 'skipped';

/** How aggressively to resolve conflicts. */
export type Strategy =
  | 'compatible'
  | { 'force-latest': { overrides: PkgName[] } };

/**
 * Which stream a line came from.
 *
 * The console drawer renders them differently, and for uv the distinction is load-bearing in a
 * way it is not for pip: uv writes its **plan** to stderr (SP-1), so "stderr" here does not mean
 * "something went wrong".
 */
export type Stream =
  | 'stdout'
  | 'stderr';

/**
 * One tool that was asked to run and did not finish.
 *
 * Deliberately `PdError`-shaped so the UI can hand it straight to `PdErrorRow` rather than
 * inventing a second error presentation for the same catalog codes.
 */
export interface ToolProblem {
  /** The catalog code, so the row is localized from the same table as every other error. */
  code: Code;
  /** Developer-facing detail. Never shown as-is (I18N §1). */
  message: string;
  /** Tail of the tool's stderr, capped as ERROR-CATALOG §3 caps every other one. */
  stderrTail?: string | null;
  /** Which tool: `deptry`, `vulture` or `ruff`. */
  tool: string;
}

/** What caused a snapshot to be taken. Shown as the trigger label on the timeline (UI-SPEC §4). */
export type Trigger =
  | { plan: { planId: string } }
  | { rollback: { restoring: string } }
  | 'manual';

/** A version string as the engine reported it. Never reshaped or localized (I18N §2). */
export type Version = string;

/**
 * One vulture finding.
 *
 * **vulture has no machine-readable output.** Its text form is
 * `<path>:<line>: <message> (<NN>% confidence)`, and `message` is `unused <typ> '<name>'` for
 * seven kinds and `unreachable code after '<token>'` for the eighth — which is why `name` is
 * optional rather than parsed out of every line. §5 has it required; amended.
 */
export interface VultureFinding {
  /** vulture's confidence percentage. Below 100 is a candidate, not a fact (§6). */
  confidence: number;
  /** 1-based. */
  line: number;
  /** The whole message, verbatim. */
  message: string;
  /** The identifier, when the message names one. */
  name?: string | null;
  /** As vulture printed it, relative to the project folder. */
  path: string;
}
