/**
 * The typed IPC boundary — ARCHITECTURE §9.
 *
 * **No component calls `invoke` directly.** Everything crosses through this module, which is the
 * one place `@tauri-apps/api/core` may be imported (enforced by `no-restricted-imports` in
 * `eslint.config.js`).
 *
 * In M2 the request/response types here are generated by `specta`/`tauri-specta` from the Rust
 * definitions so drift between core and UI becomes a compile error rather than a runtime surprise.
 * Until that generation is wired up, this module only declares the command names — which are
 * already fixed by ARCHITECTURE §7 — so the surface is reviewable now.
 */

/** Every Tauri command, per ARCHITECTURE §7. All are async and all return `Result<T, PdError>`. */
export const COMMANDS = [
  'env_scan',
  'env_add_manual',
  'env_probe',
  'pkg_list',
  'pkg_outdated',
  'index_search',
  'pkg_metadata',
  'plan_resolve',
  'plan_execute',
  'plan_cancel',
  'uninstall_guard',
  'uninstall_execute',
  'pin_list',
  'pin_add',
  'pin_remove',
  'snapshot_list',
  'snapshot_diff',
  'snapshot_rollback',
  'health_run',
  'health_fix',
  'settings_get',
  'settings_set',
  'logs_tail',
  'pip_upgrade',
  'legal_consent_get',
  'legal_consent_set',
] as const

export type Command = (typeof COMMANDS)[number]

/** Tauri event channels, per ARCHITECTURE §7. */
export const EVENTS = ['plan-progress', 'scan-progress', 'health-progress'] as const

export type EventName = (typeof EVENTS)[number]

/** The error shape every command rejects with; mirrors `pipdock_core::errors::PdError`. */
export interface PdError {
  /** Catalog code, e.g. `PD-BLD-002`. Never localized (docs/I18N.md §1). */
  code: string
  /** Developer-facing detail. The user-facing one-liner is looked up from `code`. */
  message: string
  /** Engine stderr tail, at most 40 lines (docs/ERROR-CATALOG.md §3). */
  stderrTail?: string
}
