//! TypeScript type generation for the Tauri IPC boundary.
//!
//! ARCHITECTURE §9 says the frontend types are "generated with `specta`/`tauri-specta` to prevent
//! drift". They are generated from `schemars` instead. The reasoning, so the deviation is
//! reviewable rather than mysterious:
//!
//! * specta 2 is still `2.0.0-rc`. A project that holds rusqlite at 0.37 because 0.38 needs
//!   nightly, and refuses `eslint-plugin-react` over a transitive advisory chain, cannot
//!   coherently take a pre-1.0 dependency into the crate that *is* the product.
//! * It would mean a second derive stack beside the working one: `specta::Type` on ~40 types plus
//!   hand-written impls for the newtypes and `jiff::Timestamp`.
//! * `schemars` is already a dependency, the types already derive `JsonSchema`, and
//!   `pipdock schema <T>` is already a documented public contract (CLI-SPEC §6). This is additive.
//!
//! What is given up: tauri-specta makes drift a *compile* error, and this makes it a *test*
//! failure ([`crate::bindings::tests::the_committed_bindings_are_current`]). One notch weaker, at
//! roughly a tenth of the cost. Revisit when specta 2.0 is stable — the generated file and the
//! wrapper layer are identical either way, so adopting it later is a generator swap, not a
//! redesign.
//!
//! Scope: this emits the **data types**. Command signatures are not schema-derivable and stay
//! hand-written in `ui/src/ipc/`, where there are 26 of them with one caller each.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use crate::errors::Result;
use crate::plan::{SCHEMA_TYPES, json_schema};

/// Path of the generated file, relative to the repository root.
pub const OUTPUT_PATH: &str = "ui/src/ipc/generated.ts";

/// Render every exported type as TypeScript.
///
/// # Errors
/// Propagates schema generation failures, which can only mean a type in [`SCHEMA_TYPES`] no
/// longer resolves — a compile-time mistake surfacing at runtime.
pub fn typescript() -> Result<String> {
    // Collect the root schemas and every `$defs` entry they reference. Roots and defs are merged
    // into one namespace because schemars already guarantees the names are unique.
    let mut declarations: BTreeMap<String, serde_json::Value> = BTreeMap::new();
    for name in SCHEMA_TYPES {
        let schema = json_schema(name)?;
        if let Some(defs) = schema.get("$defs").and_then(serde_json::Value::as_object) {
            for (def_name, def) in defs {
                declarations.insert(def_name.clone(), def.clone());
            }
        }
        let mut root = schema;
        if let Some(map) = root.as_object_mut() {
            map.remove("$defs");
            map.remove("$schema");
        }
        declarations.insert((*name).to_owned(), root);
    }

    let mut out = String::new();
    out.push_str(HEADER);
    for (name, schema) in &declarations {
        out.push('\n');
        out.push_str(&declaration(name, schema));
    }
    Ok(out)
}

const HEADER: &str = "\
// Generated by `cargo run -p xtask -- bindings`. Do not edit.
//
// Mirrors the Rust types exported by `pipdock schema <T>` (CLI-SPEC §6). Regenerate after
// changing any of them; `cargo test` fails while this file is stale.
//
// Command signatures are not here — they are not derivable from a schema and stay hand-written
// in `./index.ts`.
";

/// One `export interface` or `export type`.
fn declaration(name: &str, schema: &serde_json::Value) -> String {
    let mut out = String::new();
    if let Some(doc) = schema
        .get("description")
        .and_then(serde_json::Value::as_str)
    {
        out.push_str(&doc_comment(doc, ""));
    }

    // A fieldless enum, or an externally-tagged one: schemars emits `oneOf`/`anyOf` of variants.
    if let Some(variants) = schema
        .get("oneOf")
        .or_else(|| schema.get("anyOf"))
        .and_then(serde_json::Value::as_array)
    {
        let arms: Vec<String> = variants.iter().map(type_of).collect();
        let _ = writeln!(out, "export type {name} =");
        for arm in &arms {
            let _ = writeln!(out, "  | {arm}");
        }
        out.truncate(out.trim_end().len());
        out.push_str(";\n");
        return out;
    }

    // An object with named fields becomes an interface; anything else is an alias, which is how
    // the newtypes (`PkgName`, `Version`) arrive.
    let props = schema
        .get("properties")
        .and_then(serde_json::Value::as_object);
    let Some(props) = props else {
        let _ = writeln!(out, "export type {name} = {};", type_of(schema));
        return out;
    };

    let required: BTreeSet<&str> = schema
        .get("required")
        .and_then(serde_json::Value::as_array)
        .map(|r| r.iter().filter_map(serde_json::Value::as_str).collect())
        .unwrap_or_default();

    let _ = writeln!(out, "export interface {name} {{");
    for (field, spec) in props {
        if let Some(doc) = spec.get("description").and_then(serde_json::Value::as_str) {
            out.push_str(&doc_comment(doc, "  "));
        }
        // Everything schemars leaves out of `required` becomes optional. It marks every
        // `Option<T>` that way regardless of serde attributes, so `?: T | null` covers both
        // "key absent" and "key present holding null" — a superset of what the wire can carry,
        // which forces the UI to handle both rather than trusting a distinction the schema does
        // not record.
        let opt = if required.contains(field.as_str()) {
            ""
        } else {
            "?"
        };
        let _ = writeln!(out, "  {}{opt}: {};", property_key(field), type_of(spec));
    }
    out.push_str("}\n");
    out
}

/// The TypeScript type for one schema node.
fn type_of(node: &serde_json::Value) -> String {
    if let Some(reference) = node.get("$ref").and_then(serde_json::Value::as_str) {
        return reference.rsplit('/').next().unwrap_or("unknown").to_owned();
    }
    if let Some(konst) = node.get("const") {
        return json_literal(konst);
    }
    if let Some(values) = node.get("enum").and_then(serde_json::Value::as_array) {
        return union(values.iter().map(json_literal));
    }

    // `Option<T>` where T is a named type arrives as anyOf[T, null]; a tagged enum arrives as
    // oneOf of objects. Both are unions here.
    for key in ["oneOf", "anyOf", "allOf"] {
        if let Some(items) = node.get(key).and_then(serde_json::Value::as_array) {
            return union(items.iter().map(type_of));
        }
    }

    match node.get("type") {
        // `Option<String>` becomes `type: ["string", "null"]`.
        Some(serde_json::Value::Array(kinds)) => union(
            kinds
                .iter()
                .filter_map(serde_json::Value::as_str)
                .map(primitive)
                .map(str::to_owned),
        ),
        // An object carrying named fields, appearing inline rather than as a `$ref`. This is how
        // an externally-tagged enum's payload arrives: `Strategy::ForceLatest { overrides }`
        // becomes `{"force-latest": {"overrides": [...]}}`. Falling through to the `type: object`
        // arm below rendered those as `Record<string, never>` — an empty object that typechecks
        // and is wrong, so `Strategy` and `Trigger` both lost their payloads silently.
        _ if node.get("properties").is_some() => inline_object(node),
        Some(serde_json::Value::String(kind)) => match kind.as_str() {
            "array" => {
                let inner = node.get("items").map_or_else(
                    || "unknown".to_owned(),
                    |i| {
                        let rendered = type_of(i);
                        // `(A | B)[]` — without the parens this parses as `A | (B[])`.
                        if rendered.contains(" | ") {
                            format!("({rendered})")
                        } else {
                            rendered
                        }
                    },
                );
                format!("{inner}[]")
            }
            "object" => match node.get("additionalProperties") {
                Some(serde_json::Value::Bool(false)) | None => "Record<string, never>".to_owned(),
                Some(values) => format!("Record<string, {}>", type_of(values)),
            },
            other => primitive(other).to_owned(),
        },
        _ => "unknown".to_owned(),
    }
}

/// Render `{ a: A; b?: B }` for an object schema appearing in type position.
fn inline_object(node: &serde_json::Value) -> String {
    let Some(props) = node
        .get("properties")
        .and_then(serde_json::Value::as_object)
    else {
        return "Record<string, never>".to_owned();
    };
    let required: BTreeSet<&str> = node
        .get("required")
        .and_then(serde_json::Value::as_array)
        .map(|r| r.iter().filter_map(serde_json::Value::as_str).collect())
        .unwrap_or_default();

    let fields: Vec<String> = props
        .iter()
        .map(|(field, spec)| {
            let opt = if required.contains(field.as_str()) {
                ""
            } else {
                "?"
            };
            format!("{}{opt}: {}", property_key(field), type_of(spec))
        })
        .collect();
    format!("{{ {} }}", fields.join("; "))
}

/// Quote a key that is not a bare TypeScript identifier.
///
/// Serde's `rename_all = "kebab-case"` produces variant tags like `force-latest`, which is not a
/// valid identifier — unquoted it parses as a subtraction.
fn property_key(name: &str) -> String {
    let bare = !name.is_empty()
        && !name.starts_with(|c: char| c.is_ascii_digit())
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$');
    if bare {
        name.to_owned()
    } else {
        format!("'{}'", name.replace('\'', "\\'"))
    }
}

fn primitive(kind: &str) -> &'static str {
    match kind {
        "string" => "string",
        "integer" | "number" => "number",
        "boolean" => "boolean",
        "null" => "null",
        "array" => "unknown[]",
        _ => "unknown",
    }
}

fn union(parts: impl Iterator<Item = String>) -> String {
    let mut seen = Vec::new();
    for part in parts {
        if !seen.contains(&part) {
            seen.push(part);
        }
    }
    if seen.is_empty() {
        return "unknown".to_owned();
    }
    seen.join(" | ")
}

fn json_literal(value: &serde_json::Value) -> String {
    match value {
        serde_json::Value::String(s) => format!("'{}'", s.replace('\'', "\\'")),
        other => other.to_string(),
    }
}

/// A JSDoc block, so the Rust doc comments reach the editor tooltips rather than being lost.
fn doc_comment(text: &str, indent: &str) -> String {
    let lines: Vec<&str> = text.lines().collect();
    if lines.len() == 1 {
        return format!("{indent}/** {} */\n", lines[0].replace("*/", "*\\/"));
    }
    let mut out = format!("{indent}/**\n");
    for line in lines {
        let line = line.replace("*/", "*\\/");
        if line.is_empty() {
            let _ = writeln!(out, "{indent} *");
        } else {
            let _ = writeln!(out, "{indent} * {line}");
        }
    }
    let _ = writeln!(out, "{indent} */");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn generated() -> String {
        typescript().expect("every exported type has a schema")
    }

    #[test]
    fn every_exported_type_is_declared() {
        let ts = generated();
        for name in SCHEMA_TYPES {
            assert!(
                ts.contains(&format!("export interface {name} "))
                    || ts.contains(&format!("export type {name} ")),
                "{name} is missing from the bindings"
            );
        }
    }

    #[test]
    fn catalog_codes_arrive_as_a_string_union() {
        // The UI keys its error catalog off these, so they have to be literal types rather than
        // a bare `string` — a typo in a lookup should not typecheck.
        let ts = generated();
        assert!(ts.contains("export type Code ="), "{ts}");
        assert!(ts.contains("'PD-ENV-001'"), "{ts}");
        assert!(ts.contains("'PD-INT-001'"), "{ts}");
        assert!(
            !ts.contains("'EnvInterpreterMissing'"),
            "Rust variant names must not reach the bindings"
        );
    }

    #[test]
    fn properties_keep_the_wire_spelling() {
        let ts = generated();
        assert!(ts.contains("planId:"), "{ts}");
        assert!(ts.contains("stderrTail?:"), "{ts}");
        assert!(!ts.contains("plan_id"), "snake_case reached the bindings");
    }

    #[test]
    fn an_optional_field_is_both_omittable_and_nullable() {
        // schemars marks every `Option<T>` as not-required, whichever serde attribute the field
        // carries, so the schema cannot tell "key absent" (`skip_serializing_if`) from "key
        // present holding null" (`serde(default)`). `stderr_tail` is the former and
        // `hidden_user_site` the latter, and both land here identically.
        //
        // Emitting `?: T | null` for both is the safe reading: it is a superset of what the wire
        // can carry, so the UI is forced to handle absent and null alike. Narrowing either would
        // mean asserting something the schema does not actually say.
        let ts = generated();
        assert!(ts.contains("stderrTail?: string | null;"), "{ts}");
        assert!(ts.contains("hiddenUserSite?: string | null;"), "{ts}");
    }

    #[test]
    fn an_externally_tagged_variant_keeps_its_payload() {
        // `Strategy::ForceLatest { overrides }` serializes as
        // `{"force-latest": {"overrides": [...]}}`. Rendering that as `Record<string, never>`
        // typechecks and loses the field the Force-latest confirm dialog needs to name what
        // breaks (UI-SPEC §4) — generated code that is quietly wrong is worse than none.
        let ts = generated();
        assert!(
            ts.contains("'force-latest'"),
            "Strategy lost its payload:\n{ts}"
        );
        assert!(ts.contains("overrides"), "{ts}");
        assert!(
            ts.contains("'planId'") || ts.contains("planId"),
            "Trigger lost its payload:\n{ts}"
        );
        assert!(
            !ts.contains("Record<string, never>"),
            "an empty-object placeholder survived:\n{ts}"
        );
    }

    #[test]
    fn a_kebab_case_key_is_quoted() {
        // Unquoted, `force-latest: T` parses as a subtraction rather than a property.
        assert_eq!(property_key("force-latest"), "'force-latest'");
        assert_eq!(property_key("planId"), "planId");
        assert_eq!(property_key("_private"), "_private");
        assert_eq!(property_key("2fa"), "'2fa'");
    }

    #[test]
    fn a_union_inside_an_array_is_parenthesised() {
        // `A | B[]` and `(A | B)[]` are different types; getting this wrong produces bindings
        // that compile and are wrong, which is the worst outcome for generated code.
        assert_eq!(
            type_of(&serde_json::json!({
                "type": "array",
                "items": { "type": ["string", "null"] }
            })),
            "(string | null)[]"
        );
        assert_eq!(
            type_of(&serde_json::json!({ "type": "array", "items": { "type": "string" } })),
            "string[]"
        );
    }

    #[test]
    fn the_committed_bindings_are_current() {
        // This is what replaces tauri-specta's compile error. Drift fails `cargo test`, so it is
        // caught locally and in CI without a bespoke workflow step.
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("..");
        let path = root.join(OUTPUT_PATH);
        let committed = std::fs::read_to_string(&path).unwrap_or_else(|e| {
            panic!(
                "{} is missing ({e}); run `cargo run -p xtask -- bindings`",
                path.display()
            )
        });
        // Compare with line endings normalised: the file is checked out CRLF on Windows.
        let committed = committed.replace("\r\n", "\n");
        let expected = generated();
        if committed == expected {
            return;
        }

        // Report the first divergence rather than both files. `assert_eq!` over ~400 lines of
        // generated TypeScript buries the one thing the reader needs, which is the command that
        // fixes it.
        let (mut have, mut want) = (committed.lines(), expected.lines());
        let mut line = 0;
        loop {
            line += 1;
            match (have.next(), want.next()) {
                (Some(a), Some(b)) if a == b => {}
                (a, b) => panic!(
                    "{OUTPUT_PATH} is stale — run `cargo run -p xtask -- bindings`\n\
                     first difference at line {line}:\n  \
                     committed: {}\n  \
                     generated: {}",
                    a.unwrap_or("<end of file>"),
                    b.unwrap_or("<end of file>"),
                ),
            }
        }
    }
}
